accounts:
  - name: alice
    coins: ["100000000token", "1000000000000stake"]
  - name: bob
    coins: ["50000000token"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token"]
genesis:
  chain_id: "chaina"
init:
  home: "/mnt/d/cosmos/chaina/.chaina"