// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: testsuit1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetSendDataRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetSendDataRequest) Reset()         { *m = QueryGetSendDataRequest{} }
func (m *QueryGetSendDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSendDataRequest) ProtoMessage()    {}
func (*QueryGetSendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{0}
}
func (m *QueryGetSendDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSendDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSendDataRequest.Merge(m, src)
}
func (m *QueryGetSendDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSendDataRequest proto.InternalMessageInfo

func (m *QueryGetSendDataRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetSendDataResponse struct {
	SendData *SendData `protobuf:"bytes,1,opt,name=SendData,proto3" json:"SendData,omitempty"`
}

func (m *QueryGetSendDataResponse) Reset()         { *m = QueryGetSendDataResponse{} }
func (m *QueryGetSendDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSendDataResponse) ProtoMessage()    {}
func (*QueryGetSendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{1}
}
func (m *QueryGetSendDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSendDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSendDataResponse.Merge(m, src)
}
func (m *QueryGetSendDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSendDataResponse proto.InternalMessageInfo

func (m *QueryGetSendDataResponse) GetSendData() *SendData {
	if m != nil {
		return m.SendData
	}
	return nil
}

type QueryAllSendDataRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSendDataRequest) Reset()         { *m = QueryAllSendDataRequest{} }
func (m *QueryAllSendDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSendDataRequest) ProtoMessage()    {}
func (*QueryAllSendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{2}
}
func (m *QueryAllSendDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSendDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSendDataRequest.Merge(m, src)
}
func (m *QueryAllSendDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSendDataRequest proto.InternalMessageInfo

func (m *QueryAllSendDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSendDataResponse struct {
	SendData   []*SendData         `protobuf:"bytes,1,rep,name=SendData,proto3" json:"SendData,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSendDataResponse) Reset()         { *m = QueryAllSendDataResponse{} }
func (m *QueryAllSendDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSendDataResponse) ProtoMessage()    {}
func (*QueryAllSendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{3}
}
func (m *QueryAllSendDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSendDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSendDataResponse.Merge(m, src)
}
func (m *QueryAllSendDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSendDataResponse proto.InternalMessageInfo

func (m *QueryAllSendDataResponse) GetSendData() []*SendData {
	if m != nil {
		return m.SendData
	}
	return nil
}

func (m *QueryAllSendDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDataInfoRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDataInfoRequest) Reset()         { *m = QueryGetDataInfoRequest{} }
func (m *QueryGetDataInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDataInfoRequest) ProtoMessage()    {}
func (*QueryGetDataInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{4}
}
func (m *QueryGetDataInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDataInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDataInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDataInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDataInfoRequest.Merge(m, src)
}
func (m *QueryGetDataInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDataInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDataInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDataInfoRequest proto.InternalMessageInfo

func (m *QueryGetDataInfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetDataInfoResponse struct {
	DataInfo *DataInfo `protobuf:"bytes,1,opt,name=DataInfo,proto3" json:"DataInfo,omitempty"`
}

func (m *QueryGetDataInfoResponse) Reset()         { *m = QueryGetDataInfoResponse{} }
func (m *QueryGetDataInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDataInfoResponse) ProtoMessage()    {}
func (*QueryGetDataInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{5}
}
func (m *QueryGetDataInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDataInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDataInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDataInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDataInfoResponse.Merge(m, src)
}
func (m *QueryGetDataInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDataInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDataInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDataInfoResponse proto.InternalMessageInfo

func (m *QueryGetDataInfoResponse) GetDataInfo() *DataInfo {
	if m != nil {
		return m.DataInfo
	}
	return nil
}

type QueryAllDataInfoRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDataInfoRequest) Reset()         { *m = QueryAllDataInfoRequest{} }
func (m *QueryAllDataInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDataInfoRequest) ProtoMessage()    {}
func (*QueryAllDataInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{6}
}
func (m *QueryAllDataInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDataInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDataInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDataInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDataInfoRequest.Merge(m, src)
}
func (m *QueryAllDataInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDataInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDataInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDataInfoRequest proto.InternalMessageInfo

func (m *QueryAllDataInfoRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDataInfoResponse struct {
	DataInfo   []*DataInfo         `protobuf:"bytes,1,rep,name=DataInfo,proto3" json:"DataInfo,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDataInfoResponse) Reset()         { *m = QueryAllDataInfoResponse{} }
func (m *QueryAllDataInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDataInfoResponse) ProtoMessage()    {}
func (*QueryAllDataInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d666255b0547a91, []int{7}
}
func (m *QueryAllDataInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDataInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDataInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDataInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDataInfoResponse.Merge(m, src)
}
func (m *QueryAllDataInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDataInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDataInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDataInfoResponse proto.InternalMessageInfo

func (m *QueryAllDataInfoResponse) GetDataInfo() []*DataInfo {
	if m != nil {
		return m.DataInfo
	}
	return nil
}

func (m *QueryAllDataInfoResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetSendDataRequest)(nil), "user.chaina.testsuit1.QueryGetSendDataRequest")
	proto.RegisterType((*QueryGetSendDataResponse)(nil), "user.chaina.testsuit1.QueryGetSendDataResponse")
	proto.RegisterType((*QueryAllSendDataRequest)(nil), "user.chaina.testsuit1.QueryAllSendDataRequest")
	proto.RegisterType((*QueryAllSendDataResponse)(nil), "user.chaina.testsuit1.QueryAllSendDataResponse")
	proto.RegisterType((*QueryGetDataInfoRequest)(nil), "user.chaina.testsuit1.QueryGetDataInfoRequest")
	proto.RegisterType((*QueryGetDataInfoResponse)(nil), "user.chaina.testsuit1.QueryGetDataInfoResponse")
	proto.RegisterType((*QueryAllDataInfoRequest)(nil), "user.chaina.testsuit1.QueryAllDataInfoRequest")
	proto.RegisterType((*QueryAllDataInfoResponse)(nil), "user.chaina.testsuit1.QueryAllDataInfoResponse")
}

func init() { proto.RegisterFile("testsuit1/query.proto", fileDescriptor_5d666255b0547a91) }

var fileDescriptor_5d666255b0547a91 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0x69, 0x2b, 0x3a, 0x05, 0x0f, 0x83, 0xc5, 0x10, 0x64, 0xab, 0x8b, 0x34, 0xad,
	0xc8, 0x0c, 0xa9, 0x47, 0x4f, 0x2d, 0xc5, 0xe2, 0x4d, 0xe3, 0x41, 0xf0, 0x36, 0xc9, 0x8e, 0xdb,
	0x81, 0xed, 0xcc, 0x36, 0x33, 0x2b, 0x2d, 0xc5, 0x8b, 0x9f, 0x40, 0xf0, 0x20, 0x82, 0x07, 0x3f,
	0x8e, 0xc7, 0x82, 0x17, 0x8f, 0x92, 0xf8, 0x19, 0x3c, 0x4b, 0x66, 0x66, 0x77, 0xb3, 0x7f, 0xd2,
	0x4d, 0x40, 0x8f, 0xbb, 0xfb, 0x3e, 0xef, 0xfc, 0xe6, 0x79, 0xde, 0x77, 0xe1, 0x96, 0x66, 0x4a,
	0xab, 0x84, 0xeb, 0x3e, 0x39, 0x4b, 0xd8, 0xf8, 0x02, 0xc7, 0x63, 0xa9, 0x25, 0xda, 0x4a, 0x14,
	0x1b, 0xe3, 0xd1, 0x09, 0xe5, 0x82, 0xe2, 0xac, 0xa4, 0x7b, 0x2f, 0x94, 0x32, 0x8c, 0x18, 0xa1,
	0x31, 0x27, 0x54, 0x08, 0xa9, 0xa9, 0xe6, 0x52, 0x28, 0x2b, 0xea, 0x3e, 0x1a, 0x49, 0x75, 0x2a,
	0x15, 0x19, 0x52, 0xc5, 0x6c, 0x37, 0xf2, 0xae, 0x3f, 0x64, 0x9a, 0xf6, 0x49, 0x4c, 0x43, 0x2e,
	0x4c, 0xb1, 0xab, 0xed, 0xe4, 0xe7, 0x2a, 0x26, 0x82, 0x23, 0xaa, 0x69, 0xf5, 0x4b, 0x40, 0x35,
	0x7d, 0x2e, 0xde, 0x4a, 0xfb, 0xc5, 0x27, 0xf0, 0xee, 0xcb, 0x59, 0xd7, 0x63, 0xa6, 0x5f, 0x39,
	0xcd, 0x80, 0x9d, 0x25, 0x4c, 0x69, 0x74, 0x07, 0x6e, 0x70, 0x11, 0xb0, 0xf3, 0x0e, 0xb8, 0x0f,
	0x76, 0x6f, 0x0d, 0xec, 0x83, 0xff, 0x1a, 0x76, 0xaa, 0x02, 0x15, 0x4b, 0xa1, 0x18, 0x7a, 0x0a,
	0x6f, 0xa6, 0xef, 0x8c, 0x68, 0x73, 0x7f, 0x1b, 0xd7, 0x5e, 0x1a, 0x67, 0xd2, 0x4c, 0xe0, 0x53,
	0x47, 0x72, 0x10, 0x45, 0x65, 0x92, 0x67, 0x10, 0xe6, 0x97, 0x75, 0x9d, 0x77, 0xb0, 0x75, 0x06,
	0xcf, 0x9c, 0xc1, 0xd6, 0x67, 0xe7, 0x0c, 0x7e, 0x41, 0x43, 0xe6, 0xb4, 0x83, 0x39, 0xa5, 0xff,
	0x0d, 0x38, 0xf8, 0xc2, 0x19, 0xb5, 0xf0, 0x6b, 0x2b, 0xc1, 0xa3, 0xe3, 0x02, 0x61, 0xdb, 0x10,
	0xf6, 0x1a, 0x09, 0xed, 0xc9, 0x05, 0xc4, 0xbd, 0x3c, 0x8f, 0x23, 0x97, 0x54, 0xea, 0xc2, 0x6d,
	0xd8, 0xe6, 0x81, 0xb9, 0xfd, 0xfa, 0xa0, 0xcd, 0x83, 0xf9, 0x24, 0xf2, 0xd2, 0xfc, 0x32, 0xe9,
	0xbb, 0x86, 0x24, 0x32, 0x69, 0x26, 0x98, 0x4f, 0xa2, 0xcc, 0xf0, 0x3f, 0x92, 0x68, 0x80, 0x5f,
	0x5b, 0x09, 0xfe, 0x9f, 0x25, 0xb1, 0xff, 0x67, 0x1d, 0x6e, 0x18, 0x44, 0xf4, 0x15, 0xe4, 0xa3,
	0x81, 0xf0, 0x02, 0x94, 0x05, 0x5b, 0xd4, 0x25, 0x4b, 0xd7, 0x5b, 0x06, 0x9f, 0x7c, 0xf8, 0xf1,
	0xfb, 0x53, 0x7b, 0x0f, 0xf5, 0xc8, 0x4c, 0x48, 0xac, 0x90, 0x54, 0x57, 0x9b, 0x5c, 0x9a, 0x85,
	0x7c, 0x8f, 0x3e, 0x03, 0xb8, 0x99, 0x76, 0x39, 0x88, 0xa2, 0xeb, 0x09, 0xab, 0xdb, 0x75, 0x3d,
	0x61, 0xcd, 0xa6, 0xf8, 0x3d, 0x43, 0xf8, 0x00, 0x6d, 0x37, 0x10, 0xa2, 0x2f, 0x20, 0x4f, 0xb2,
	0xd1, 0xb8, 0xd2, 0xa8, 0x35, 0x1a, 0x57, 0x1e, 0x1b, 0xff, 0xb1, 0xc1, 0xda, 0x41, 0x0f, 0x17,
	0x60, 0xa5, 0x7f, 0x3e, 0x72, 0xc9, 0x03, 0xeb, 0x5a, 0xda, 0x62, 0x19, 0xd7, 0x56, 0xc2, 0xab,
	0x99, 0xea, 0x46, 0xd7, 0x52, 0xbc, 0xc3, 0xc3, 0xef, 0x13, 0x0f, 0x5c, 0x4d, 0x3c, 0xf0, 0x6b,
	0xe2, 0x81, 0x8f, 0x53, 0xaf, 0x75, 0x35, 0xf5, 0x5a, 0x3f, 0xa7, 0x5e, 0xeb, 0xcd, 0x6e, 0xc8,
	0xf5, 0x49, 0x32, 0xc4, 0x23, 0x79, 0x5a, 0x68, 0x72, 0x3e, 0xd7, 0x46, 0x5f, 0xc4, 0x4c, 0x0d,
	0x6f, 0x98, 0xbf, 0xfb, 0x93, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x6b, 0x91, 0x53, 0x8b,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	SendData(ctx context.Context, in *QueryGetSendDataRequest, opts ...grpc.CallOption) (*QueryGetSendDataResponse, error)
	SendDataAll(ctx context.Context, in *QueryAllSendDataRequest, opts ...grpc.CallOption) (*QueryAllSendDataResponse, error)
	DataInfo(ctx context.Context, in *QueryGetDataInfoRequest, opts ...grpc.CallOption) (*QueryGetDataInfoResponse, error)
	DataInfoAll(ctx context.Context, in *QueryAllDataInfoRequest, opts ...grpc.CallOption) (*QueryAllDataInfoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SendData(ctx context.Context, in *QueryGetSendDataRequest, opts ...grpc.CallOption) (*QueryGetSendDataResponse, error) {
	out := new(QueryGetSendDataResponse)
	err := c.cc.Invoke(ctx, "/user.chaina.testsuit1.Query/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SendDataAll(ctx context.Context, in *QueryAllSendDataRequest, opts ...grpc.CallOption) (*QueryAllSendDataResponse, error) {
	out := new(QueryAllSendDataResponse)
	err := c.cc.Invoke(ctx, "/user.chaina.testsuit1.Query/SendDataAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DataInfo(ctx context.Context, in *QueryGetDataInfoRequest, opts ...grpc.CallOption) (*QueryGetDataInfoResponse, error) {
	out := new(QueryGetDataInfoResponse)
	err := c.cc.Invoke(ctx, "/user.chaina.testsuit1.Query/DataInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DataInfoAll(ctx context.Context, in *QueryAllDataInfoRequest, opts ...grpc.CallOption) (*QueryAllDataInfoResponse, error) {
	out := new(QueryAllDataInfoResponse)
	err := c.cc.Invoke(ctx, "/user.chaina.testsuit1.Query/DataInfoAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	SendData(context.Context, *QueryGetSendDataRequest) (*QueryGetSendDataResponse, error)
	SendDataAll(context.Context, *QueryAllSendDataRequest) (*QueryAllSendDataResponse, error)
	DataInfo(context.Context, *QueryGetDataInfoRequest) (*QueryGetDataInfoResponse, error)
	DataInfoAll(context.Context, *QueryAllDataInfoRequest) (*QueryAllDataInfoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SendData(ctx context.Context, req *QueryGetSendDataRequest) (*QueryGetSendDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}
func (*UnimplementedQueryServer) SendDataAll(ctx context.Context, req *QueryAllSendDataRequest) (*QueryAllSendDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataAll not implemented")
}
func (*UnimplementedQueryServer) DataInfo(ctx context.Context, req *QueryGetDataInfoRequest) (*QueryGetDataInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataInfo not implemented")
}
func (*UnimplementedQueryServer) DataInfoAll(ctx context.Context, req *QueryAllDataInfoRequest) (*QueryAllDataInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataInfoAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSendDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.chaina.testsuit1.Query/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SendData(ctx, req.(*QueryGetSendDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SendDataAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSendDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SendDataAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.chaina.testsuit1.Query/SendDataAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SendDataAll(ctx, req.(*QueryAllSendDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DataInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDataInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DataInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.chaina.testsuit1.Query/DataInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DataInfo(ctx, req.(*QueryGetDataInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DataInfoAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDataInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DataInfoAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.chaina.testsuit1.Query/DataInfoAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DataInfoAll(ctx, req.(*QueryAllDataInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.chaina.testsuit1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendData",
			Handler:    _Query_SendData_Handler,
		},
		{
			MethodName: "SendDataAll",
			Handler:    _Query_SendDataAll_Handler,
		},
		{
			MethodName: "DataInfo",
			Handler:    _Query_DataInfo_Handler,
		},
		{
			MethodName: "DataInfoAll",
			Handler:    _Query_DataInfoAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testsuit1/query.proto",
}

func (m *QueryGetSendDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSendDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSendDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSendDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSendDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSendDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SendData != nil {
		{
			size, err := m.SendData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSendDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSendDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSendDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSendDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSendDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSendDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SendData) > 0 {
		for iNdEx := len(m.SendData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SendData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDataInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDataInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDataInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDataInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDataInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDataInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DataInfo != nil {
		{
			size, err := m.DataInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDataInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDataInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDataInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDataInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDataInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDataInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DataInfo) > 0 {
		for iNdEx := len(m.DataInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DataInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetSendDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSendDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SendData != nil {
		l = m.SendData.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSendDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSendDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SendData) > 0 {
		for _, e := range m.SendData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDataInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDataInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DataInfo != nil {
		l = m.DataInfo.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDataInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDataInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DataInfo) > 0 {
		for _, e := range m.DataInfo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetSendDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSendDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSendDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSendDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSendDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSendDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SendData == nil {
				m.SendData = &SendData{}
			}
			if err := m.SendData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSendDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSendDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSendDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSendDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSendDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSendDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendData = append(m.SendData, &SendData{})
			if err := m.SendData[len(m.SendData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDataInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDataInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDataInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDataInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDataInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDataInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DataInfo == nil {
				m.DataInfo = &DataInfo{}
			}
			if err := m.DataInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDataInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDataInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDataInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDataInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDataInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDataInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataInfo = append(m.DataInfo, &DataInfo{})
			if err := m.DataInfo[len(m.DataInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
